name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: src/Dump1090.sln
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        BUILD_CONFIGURATION: [ Release ]
        BUILD_PLATFORM:      [ x64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      

      run: |
         msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
         7z a Dump1090.zip D:/a/Dump1090/
      shell: cmd

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: Dump1090
          path:  Dump1090.zip

# test:
#   steps:
#    run:  start dump1090 --max-messages 20 --debug Gn --net --logfile dump1090.log
#          py.exe -3 tools\SBS_client.py --host localhost --wait 10 --port 30001 raw-out
#
